# Project metadata

[tool.pdm.version]
source = "scm"

[project]
name = "amaranth-orchard"
dynamic = ["version"]
description = "curated collection of Amaranth cores"
authors = [
    {name = "Myrtle Shah", email = "gatecat@ds0.me" },
]
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE.txt"}

requires-python = ">=3.10"
dependencies = [
    "amaranth>=0.5,<0.6",
    "chipflow-lib @ git+https://github.com/ChipFlow/chipflow-lib.git",
    "amaranth-soc @ git+https://github.com/amaranth-lang/amaranth-soc@0ad5e245dd130d66a0a16663116ad0c1fe7a8956",
    "amaranth-stdio @ git+https://github.com/amaranth-lang/amaranth-stdio",
]

# Build system configuration

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

# Development workflow configuration

[tool.pyright]
diagnosticMode=false
typeCheckingMode = "off"
reportInvalidTypeForm = false
reportMissingImports = false
reportUnboundVariable = false

[tool.ruff.lint]
ignore = ['F403', 'F405']
